# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

docker_build(
    "simple-health-client",
    context="../..",
    dockerfile="./Dockerfile"
)

# Deploy the service
objects = decode_yaml_stream(read_file("deployment.yaml"))

# With the deployment platform connector the client publishes to it directly,
# over TLS and with the same projected token.
if os.getenv('USE_DEPLOYMENT_PLATFORM_CONNECTOR', '0') == '1':
    for obj in objects:
        if obj.get('kind') != 'Deployment':
            continue
        pod = obj['spec']['template']['spec']
        pod['volumes'].append({'name': 'deployment-ca', 'secret': {
            'secretName': 'platform-connector-deployment-grpc-cert',
            'items': [{'key': 'ca.crt', 'path': 'ca.crt'}],
        }})
        for container in pod['containers']:
            container['env'] += [
                {'name': 'HEALTH_PUBLISH_TARGET', 'value': 'platform-connector-deployment.nvsentinel.svc.cluster.local:50051'},
                {'name': 'HEALTH_PUBLISH_TOKEN_PATH', 'value': '/var/run/secrets/nvsentinel/platform-connector/token'},
                {'name': 'HEALTH_PUBLISH_TLS_CA_FILE', 'value': '/etc/nvsentinel/deployment-ca/ca.crt'},
            ]
            container['volumeMounts'].append(
                {'name': 'deployment-ca', 'mountPath': '/etc/nvsentinel/deployment-ca', 'readOnly': True})

k8s_yaml(encode_yaml_stream(objects))

# Port forward for testing
k8s_resource("simple-health-client", port_forwards="8080:8080")
