# Copyright (c) 2025, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Publish Containers

on:
  push:
    tags:
      - 'v*'
    branches:
      - main
  workflow_dispatch:
    inputs:
      tag:
        description: 'Existing tag to build and publish (e.g., v1.2.3)'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read       # Required for checking out code
  packages: write      # Required for publishing containers to ghcr.io
  actions: read        # Required for artifact operations
  security-events: write
  id-token: write
  attestations: write

jobs:
  prepare-environment:
    uses: ./.github/workflows/prepare-environment.yml

  build-image-list:
    runs-on: linux-amd64-cpu32
    timeout-minutes: 60
    needs: prepare-environment
    outputs:
      versions: ${{ steps.build-list.outputs.versions }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          go-version: ${{ needs.prepare-environment.outputs.go_version }}
          python-version: ${{ needs.prepare-environment.outputs.python_version }}
          poetry-version: ${{ needs.prepare-environment.outputs.poetry_version }}
          golangci-lint-version: ${{ needs.prepare-environment.outputs.golangci_lint_version }}
          protobuf-version: ${{ needs.prepare-environment.outputs.protobuf_version }}
          protoc-gen-go-version: ${{ needs.prepare-environment.outputs.protoc_gen_go_version }}
          protoc-gen-go-grpc-version: ${{ needs.prepare-environment.outputs.protoc_gen_go_grpc_version }}
          grpcio-tools-version: ${{ needs.prepare-environment.outputs.grpcio_tools_version }}
          black-version: ${{ needs.prepare-environment.outputs.black_version }}
          shellcheck-version: ${{ needs.prepare-environment.outputs.shellcheck_version }}
          ko-version: ${{ needs.prepare-environment.outputs.ko_version }}

      - name: Compute ref name with short SHA
        id: ref-name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "value=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "value=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "value=${{ github.ref_name }}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Build image list
        id: build-list
        env:
          CI_COMMIT_REF_NAME: ${{ steps.ref-name.outputs.value }}
        run: |
          chmod +x ./scripts/build_image_list.sh
          ./scripts/build_image_list.sh
          cat versions.txt

      - name: Upload versions.txt
        uses: actions/upload-artifact@v4
        with:
          name: versions
          path: versions.txt
          retention-days: 90

  container-publish:
    runs-on: linux-amd64-cpu4
    timeout-minutes: 60
    needs: prepare-environment
    strategy:
      matrix:
        include:
          - component: gpu-health-monitor-dcgm3
            make_command: 'make -C health-monitors/gpu-health-monitor docker-publish-dcgm3'
            container_name: 'nvsentinel/gpu-health-monitor'
            tag_suffix: '-dcgm-3.x'
          - component: gpu-health-monitor-dcgm4
            make_command: 'make -C health-monitors/gpu-health-monitor docker-publish-dcgm4'
            container_name: 'nvsentinel/gpu-health-monitor'
            tag_suffix: '-dcgm-4.x'
          - component: syslog-health-monitor
            make_command: 'make -C health-monitors/syslog-health-monitor docker-publish'
            container_name: 'nvsentinel/syslog-health-monitor'
          - component: log-collector
            make_command: 'make -C nvsentinel-log-collector docker-publish-log-collector'
            container_name: 'nvsentinel/log-collector'
          - component: file-server-cleanup
            make_command: 'make -C nvsentinel-log-collector docker-publish-file-server-cleanup'
            container_name: 'nvsentinel/file-server-cleanup'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.tag || github.ref }}

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          go-version: ${{ needs.prepare-environment.outputs.go_version }}
          python-version: ${{ needs.prepare-environment.outputs.python_version }}
          poetry-version: ${{ needs.prepare-environment.outputs.poetry_version }}
          golangci-lint-version: ${{ needs.prepare-environment.outputs.golangci_lint_version }}
          protobuf-version: ${{ needs.prepare-environment.outputs.protobuf_version }}
          protoc-gen-go-version: ${{ needs.prepare-environment.outputs.protoc_gen_go_version }}
          protoc-gen-go-grpc-version: ${{ needs.prepare-environment.outputs.protoc_gen_go_grpc_version }}
          grpcio-tools-version: ${{ needs.prepare-environment.outputs.grpcio_tools_version }}
          black-version: ${{ needs.prepare-environment.outputs.black_version }}
          shellcheck-version: ${{ needs.prepare-environment.outputs.shellcheck_version }}
          ko-version: ${{ needs.prepare-environment.outputs.ko_version }}

      - name: Compute ref name with short SHA
        id: ref-name
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "value=${{ github.event.inputs.tag }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "value=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
            echo "value=${{ github.ref_name }}-${SHORT_SHA}" >> $GITHUB_OUTPUT
          fi

      - name: Publish container for ${{ matrix.component }}
        uses: ./.github/actions/publish-container
        env:
          CI_COMMIT_REF_NAME: ${{ steps.ref-name.outputs.value }}
        with:
          make_command: ${{ matrix.make_command }}
          registry_password: ${{ secrets.GITHUB_TOKEN }}
          container_name: ${{ matrix.container_name }}
          tag_suffix: ${{ matrix.tag_suffix }}


  # Build images using ko and attest provenance
  # Once validated, this will replace the container-publish job above
  build-images:
    runs-on: linux-amd64-cpu32
    timeout-minutes: 60
    needs: prepare-environment
    permissions:
      contents: read
      packages: write
      id-token: write
      attestations: write
    env:
      KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
      VERSION: ${{ github.ref_name }}
      GIT_COMMIT: ${{ github.sha }}
    outputs:
      images: ${{ steps.ko-build.outputs.images }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  # v5.0.0

      - name: Setup build environment
        uses: ./.github/actions/setup-build-env
        with:
          go-version: ${{ needs.prepare-environment.outputs.go_version }}
          python-version: ${{ needs.prepare-environment.outputs.python_version }}
          poetry-version: ${{ needs.prepare-environment.outputs.poetry_version }}
          golangci-lint-version: ${{ needs.prepare-environment.outputs.golangci_lint_version }}
          protobuf-version: ${{ needs.prepare-environment.outputs.protobuf_version }}
          protoc-gen-go-version: ${{ needs.prepare-environment.outputs.protoc_gen_go_version }}
          protoc-gen-go-grpc-version: ${{ needs.prepare-environment.outputs.protoc_gen_go_grpc_version }}
          grpcio-tools-version: ${{ needs.prepare-environment.outputs.grpcio_tools_version }}
          black-version: ${{ needs.prepare-environment.outputs.black_version }}
          shellcheck-version: ${{ needs.prepare-environment.outputs.shellcheck_version }}
          ko-version: ${{ needs.prepare-environment.outputs.ko_version }}

      - name: Authenticate to GHCR
        shell: bash
        run: echo ${{ secrets.GITHUB_TOKEN }} | ko login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Using Ko
        id: ko-build
        run: scripts/buildko.sh

  attest:
    needs: build-images
    runs-on: linux-amd64-cpu32
    permissions:
      packages: write
      id-token: write
      attestations: write
    strategy:
      matrix:
        image: ${{ fromJson(needs.build-images.outputs.images) }}
    steps:
      - name: Authenticate to GHCR
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef  # v3.6.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Attest build provenance
        id: attest
        uses: actions/attest-build-provenance@977bb373ede98d70efdf65b84cb5f73e068dcc2a  # v3.0.0
        with:
          subject-name: ${{ matrix.image.name }}
          subject-digest: ${{ matrix.image.digest }}
          push-to-registry: true